# Generated by Django 4.1.1 on 2022-09-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female')], max_length=10),
        ),
    ]
