# Generated by Django 4.1.1 on 2022-09-12 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0004_currency_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=40)),
                ('transaction_amount', models.IntegerField()),
                ('transaction_type', models.CharField(max_length=20)),
                ('transaction_charge', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('message', models.CharField(max_length=20, null=True)),
                ('destination_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_destination_account', to='Wallet.wallet')),
                ('origin_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_origin_account', to='Wallet.wallet')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_wallet', to='Wallet.wallet')),
            ],
        ),
    ]
