# Generated by Django 4.1.1 on 2022-09-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0005_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.BigIntegerField()),
                ('date_of_reward', models.DateTimeField()),
                ('transaction_amount', models.IntegerField()),
            ],
        ),
    ]
