# Generated by Django 4.1.1 on 2022-09-12 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0006_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=20)),
                ('loan_type', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('interest', models.IntegerField()),
                ('loan_term', models.IntegerField()),
                ('payment_due_date', models.DateTimeField()),
                ('loan_balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField()),
                ('title', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField()),
                ('recepients', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recepients', to='Wallet.customer')),
            ],
        ),
    ]
