# Generated by Django 4.1.1 on 2022-09-12 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0009_thirdparty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(default=False)),
                ('card_name', models.CharField(blank=True, max_length=30)),
                ('card_type', models.CharField(blank=True, default=False, max_length=30)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime.now)),
                ('security_code', models.IntegerField(default=False)),
                ('date_ofissue', models.DateTimeField(default=datetime.datetime.now)),
                ('account_number', models.IntegerField(default=False)),
            ],
        ),
    ]
