# Generated by Django 4.1.1 on 2022-09-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0010_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='are_you_employment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='nationality',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
