# Generated by Django 4.1.1 on 2022-09-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0011_customer_are_you_employment_customer_marital_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='status',
            new_name='wallet_status',
        ),
    ]
